# name: docker

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   Deploy-to-dev:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to Aliyun Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ${{ secrets.ALIYUN_REGISTRY }}
#           username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
#           password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

#       - name: Build and push xray
#         uses: docker/build-push-action@v3
#         with:
#           file: ./xray/Dockerfile
#           context: ./xray
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: |
#             registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:xray-v20

#       - name: Build and push webgoat
#         uses: docker/build-push-action@v3
#         with:
#           file: ./webgoat/Dockerfile
#           context: ./webgoat
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: |
#             registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:webgoat-v20

#       - name: Build and push openrasp
#         uses: docker/build-push-action@v3
#         with:
#           file: ./openrasp/Dockerfile
#           context: ./openrasp
#           platforms: linux/amd64
#           push: true
#           tags: |
#             registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:openrasp-v20

#       - name: Build and push BenchmarkJava
#         uses: docker/build-push-action@v3
#         with:
#           file: ./BenchmarkJava/Dockerfile
#           context: ./BenchmarkJava
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: |
#             registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:benchmark-v20
